classifications:
  - name: Bug fix
    description: A change that addresses incorrect or unexpected behavior in the
      existing code.
  - name: Feature
    description: Introduction of a new feature or a notable enhancement to existing
      functionality.
  - name: Refactor
    description: Reorganization of code for improved clarity, maintainability, or
      structure without changing external behavior.
  - name: Performance
    description: Changes that optimize the speed, efficiency, or scalability of the
      application.
  - name: Security
    description: A change that addresses a security vulnerability or hardens the
      system's security posture.
  - name: Documentation
    description: Any PR that updates or adds documentation (README, user manuals,
      code comments, etc.).
  - name: Testing
    description: Additions or revisions to tests (unit, integration, end-to-end)
      aimed at improving coverage or reliability.
  - name: Build/CI
    description: Modifications to library/package dependencies, build scripts, or
      continuous integration configuration.
  - name: Chore
    description: General housekeeping that doesn't fall under the above categories
      (e.g., version bumps, minor configurations, or grooming tasks).
  - name: UX
    description: Changes specifically aimed at user interface or user experience
      improvements.
  - name: Other
    description: Changes that don't fit into any other category.
templates:
  - name: Default
    groupInstructions: Highlight the most important changes in the diff. Tests,
      documentation, dependencies, and other changes should have a low priority.
    language: English
    writingStyle: Normal
    technicalKnowledge: 5
  - name: Executive summary
    groupInstructions: >
      I am a non technical executive. I just want to know what's going on with
      each PR. Please provide a high level summary of the changes. Only show me
      code if it's critically necessary for understanding..otherwise I just want
      the executive summary, especially as it relates to the intent of the PR. 


      Use the following format


      ## Executive Summary


      [summary]


      ### Background


      [summary of any related issues or background information that helps me
      understand purpose or intent]


      ### Changes


      [summary of changes]


      ### Glossary


      [define any technical terms used in previous sections]
    language: Spanish
    writingStyle: Concise
    technicalKnowledge: 1
  - name: Risk assessment
    groupInstructions: "I am a security engineer. I need to understand the riskiest
      parts of this pull request. Please highlight potential areas of concern
      first. If a change doesn't affect runtime, don't show it to me at all--i
      just don't care.  "
    language: English
    writingStyle: Normal
    technicalKnowledge: 5
  - name: Docs writer
    groupInstructions: >-
      I am a technical writer for our documentation team.


      Before generating your walkthrough, please give me some sample docs that I
      can use to expand our documentation site.  Please provide a detailed
      description of any changes that have user-facing impact. Write a detailed
      description and provide sample code when necessary.  Use the following
      template


      ## Changes necessary to docs


      [describe how I should change our docs]


      ## Sample code


      [share sample code that would be relevant for our users]


      ---


      When generating the walkthrough, please skip testing files or other
      secondary changes that do not modify actual runtime or customer
      experience. 
    language: English
    writingStyle: Explanatory
    technicalKnowledge: 5
