technicalKnowledge: 5
instructions: ""
language: English
writingStyle: Normal
classifications:
  - name: Bug fix
    description: A change that addresses incorrect or unexpected behavior in the
      existing code.
  - name: New feature
    description: "A PR that delivers new or exciting customer value. "
  - name: Security
    description: A change that addresses a security vulnerability or hardens the
      system's security posture.
  - name: Low priority
    description: >-
      Mark as low priority if any of the following conditions are met:


      - PR updates or adds documentation (README, user manuals, code comments,
      etc.).

      - Additions or revisions to tests (unit, integration, end-to-end) aimed at
      improving coverage or reliability.

      - Modifications to library/package dependencies, build scripts, or
      continuous integration configuration.

      - General housekeeping that doesn't fall under the above categories (e.g.,
      version bumps, minor configurations, or grooming tasks).

      - Changes that optimize the speed, efficiency, or scalability of the
      application.

      - Reorganization of code for improved clarity, maintainability, or
      structure without changing external behavior.
  - name: UX and design improvements
    description: Changes specifically aimed at user interface or design improvements
  - name: Other
    description: Changes that don't fit into any other category.
  - name: Accessibility
    description: Changes specifically aimed at improving accessibility
templates:
  - name: Default
    instructions: >-
      - Walk through the changes in a clear and organized manner

      - The changes most reflective of the PRs intent should be shown first

      - Documentation, tests, and cosmetic changes should be shown last


      For each group, you must answer the following questions in the group's
      description:

      - Is there a new API introduced?

      - Is a new library introduced?

      - Why is it written this way?

      - Is there any security concerns here?
  - name: Docs
    instructions: I am a copywriter, please show documentation changes first
